/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#003b39",
        "inverse-surface": "#2a3234",
        "surface-tint": "#006a67",
        "primary-fixed": "#83f5f0",
        "on-secondary-fixed": "#00201f",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#bee8e5",
        "on-primary": "#ffffff",
        "outline-variant": "#bcc9c8",
        "primary": "#006a67",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface-container": "#e8eff2",
        "inverse-primary": "#65d8d4",
        "surface-variant": "#dde4e7",
        "surface-dim": "#d4dbde",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#77320f",
        "primary-fixed-dim": "#65d8d4",
        "secondary": "#3e6563",
        "outline": "#6d7a78",
        "on-surface-variant": "#3d4948",
        "on-background": "#161d1f",
        "on-surface": "#161d1f",
        "secondary-fixed": "#c1ebe8",
        "on-tertiary-fixed": "#360f00",
        "on-primary-fixed-variant": "#00504e",
        "primary-container": "#30ada9",
        "surface-container-highest": "#dde4e7",
        "tertiary": "#954925",
        "error-container": "#ffdad6",
        "surface-container-high": "#e2e9ec",
        "tertiary-container": "#e1845b",
        "on-tertiary-container": "#5e2000",
        "tertiary-fixed": "#ffdbcd",
        "on-primary-fixed": "#00201f",
        "on-secondary-container": "#426967",
        "surface-container-low": "#eef5f8",
        "inverse-on-surface": "#ebf2f5",
        "on-secondary-fixed-variant": "#254d4b",
        "surface": "#f3fafd",
        "surface-bright": "#f3fafd",
        "background": "#f3fafd",
        "tertiary-fixed-dim": "#ffb597",
        "secondary-fixed-dim": "#a5cecc"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
}
