export const viewerCopy = {
  title: '3D Viewer',
  description: 'Inspect the generated creation from different angles before editing.',
  editTitle: '3D Viewer · Edit Mode',
  editDescription: 'Edit mode keeps camera movement locked and exposes guided angles + scene asset management.',
  stageAriaLabel: '3D scene viewport',
  controlsAriaLabel: 'Viewer navigation controls',
  quickActionsAriaLabel: 'Viewer quick actions',
  interactionHint: 'Drag to rotate, use wheel/pinch to zoom, and click any zone in the scene to move camera focus.',
  rotateCoachmark: 'Drag to rotate',
  keyboardHint: 'Viewer keeps controls minimal. Use Edit mode for scene modifications.',
  creationLabel: 'Creation',
  sceneLabel: 'Scene',
  controls: {
    title: 'Navigation controls',
    moveTitle: 'Move',
    zoomTitle: 'Zoom',
    rotateTitle: 'Rotate',
    reset: 'Reset camera',
    collapse: 'Hide controls',
    expand: 'Show controls',
    moveUp: 'Move up',
    moveRight: 'Move right',
    moveDown: 'Move down',
    moveLeft: 'Move left',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    rotateLeft: 'Rotate left',
    rotateRight: 'Rotate right',
  },
  quickActions: {
    enableEditMode: 'Enable Edit Mode',
    disableEditMode: 'Disable Edit Mode',
    editButton: 'Edit',
    editEnabled: 'Enabled',
    editDisabled: 'Disabled',
    openProjectMenu: 'Open project menu',
    closeProjectMenu: 'Close project menu',
    openGallery: 'Go to Gallery',
    openAssetLibrary: 'Open Asset Library',
    openUpload: 'Go to Upload',
    collapseCreateDock: 'Hide create panel',
    expandCreateDock: 'Show create panel',
    openZoomHelp: 'Open viewer tutorial',
  },
  share: {
    triggerLabel: 'Share',
    dialogTitle: 'Share this viewer',
    dialogDescription: 'Send a view-only link or capture a screenshot from the current render.',
    closeDialogCta: 'Close share modal',
    shareLinkTitle: 'Share view-only link',
    shareLinkDescription: 'Anyone with this link can open the viewer, but edit mode will remain disabled.',
    shareLinkFieldLabel: 'View-only link',
    copyLinkCta: 'Copy link',
    copiedLinkStatus: 'Link copied to clipboard.',
    copyLinkError: 'Could not copy link. Please copy it manually.',
    screenshotTitle: 'Capture screenshot',
    screenshotDescription: 'Save a PNG snapshot from the current render to your device or copy it to clipboard.',
    screenshotDownloadCta: 'Download PNG',
    screenshotClipboardCta: 'Copy image',
    screenshotSavedStatus: 'Screenshot saved to your device.',
    screenshotCopiedStatus: 'Screenshot copied to clipboard.',
    screenshotClipboardUnsupported: 'Clipboard image copy is not supported in this browser.',
    screenshotError: 'Could not capture screenshot. Please try again.',
  },
  helpTutorial: {
    title: 'Viewer quick tutorial',
    description: 'Short guided tour to understand navigation, edit mode, and asset workflows.',
    closeCta: 'Close tutorial',
    previousStepCta: 'Previous',
    nextStepCta: 'Next',
    finishCta: 'Finish tutorial',
    stepLabel: 'Step',
    stepConnector: 'of',
    jumpToStepLabel: 'Go to step',
    videoPlaceholderTitle: 'Video walkthrough',
    videoPlaceholderDescription: 'Coming soon: video tutorial will be added in this section.',
    steps: [
      { title: 'Explore scene in view mode', description: 'Drag in scene to rotate, use wheel or pinch to zoom, and click zone to move camera focus.' },
      { title: 'Open project context', description: 'Top-left project menu shows current scenario and objects, plus quick links to Gallery, Asset Library, and Upload.' },
      { title: 'Use Create panel', description: 'Bottom Create panel lets you choose target (Object or Scenario), select input mode, and continue generation in Upload.' },
      { title: 'Switch to edit mode', description: 'Use Edit button on top-right to lock camera movement and expose angle presets for precise scene inspection.' },
      { title: 'Import and place assets', description: 'In edit mode, import models from Sketchfab or add generated assets to test composition before final generation.' },
    ],
  },
  quickCreate: {
    title: 'Create New',
    targetLabel: 'Target',
    targetObject: 'Object',
    targetScenario: 'Scenario',
    modeLabel: 'Input',
    modeImage: 'Image',
    modeVideo: 'Video',
    modePrompt: 'Prompt',
    promptLabel: 'Prompt',
    promptPlaceholder: 'Describe mood, materials, lighting, and layout.',
    imageHint: 'Image mode selected. Upload your references in the next step.',
    videoHint: 'Video mode selected. Upload your clip in the next step.',
    continueCta: 'Continue in Upload',
  },
  editorMode: {
    activeBadge: 'Edit mode active',
    lockedCameraHint: 'Camera movement is locked. Use angle presets to inspect reconstruction details.',
    viewsTitle: 'Reconstruction angles',
    viewsAriaLabel: 'Preset camera angles for edit mode',
    assetsTitle: 'Scene assets',
    assetsSubtitle: 'Timeline-style manager for scenario, objects, and light resources currently in this scene.',
    assetsEmpty: 'No assets yet. Generate one from this panel or import from your library.',
    selectedAssetTitle: 'Selected asset',
    positionLabel: 'Position',
    rotationLabel: 'Rotation',
    scaleLabel: 'Scale',
    addPanelTitle: 'Asset intake panel',
    addPanelDescription: 'Generate assets for this scene, push to Upload for full generation, or import from your library.',
    generateInSceneCta: 'Generate in Scene',
    sendToUploadCta: 'Continue in Upload',
    importFromLibraryCta: 'Import from Sketchfab',
    customAssetNameLabel: 'Custom asset name',
    customAssetNamePlaceholder: 'Example: Accent chair variant',
    customAssetTypeLabel: 'Asset type',
    customAssetAddCta: 'Add asset to scene',
    baseLightsTitle: 'Base lights',
    baseLightsSubtitle: 'Apply Poly Haven HDRIs to set ambient reflections and mood.',
    baseLightsEmpty: 'No base lights available. Run local light sync to populate this list.',
    baseLightsNoResults: 'No lights match current search/filter.',
    baseLightsSearchLabel: 'Search lights',
    baseLightsSearchPlaceholder: 'Search by title, author, or category',
    baseLightsCategoryLabel: 'Category',
    baseLightsCategoryAll: 'All categories',
    defaultLightLabel: 'Default light',
    changeLightCta: 'Change light',
    createLightCta: 'Create light',
    customLightsTitle: 'Custom lights',
    customLightSourceLabel: 'Based on',
    customLightNamePrefix: 'Custom light',
    customLightSourceNamePrefix: 'Light',
    applyLightCta: 'Apply',
    appliedLightBadge: 'Active',
    lightUseDefaultCta: 'Use default light',
    lightSourceLabel: 'Source',
    lightStatusLabel: 'Light status',
    lightApplyingStatus: 'Applying light composition...',
    lightAppliedStatus: 'Active light',
    lightFallbackStatus: 'Default fallback light active.',
    lightApplyError: 'Could not apply selected light composition.',
    lightComposerTitle: 'Light composer',
    lightComposerSubtitle: 'Create custom light preset with live preview and save it to this project.',
    lightComposerNameLabel: 'Preset name',
    lightComposerNamePlaceholder: 'Example: Sunset warm key',
    lightComposerSourceLabel: 'Base light',
    lightComposerDefaultSourceLabel: 'App default light rig',
    lightComposerGlobalPresetsTitle: 'Global presets',
    lightComposerViewportTitle: 'Live viewport',
    lightComposerViewportHint: 'Preview scene above while tuning source map and values.',
    lightComposerMapTitle: 'Light map',
    lightComposerMapHint: 'Drag to move on X/Z. Shift + Drag to adjust height (Y).',
    lightComposerMapAxisX: 'X axis',
    lightComposerMapAxisZ: 'Z axis',
    lightComposerRotationLabel: 'Rotation',
    lightComposerExposureLabel: 'Exposure',
    lightComposerEnvironmentIntensityLabel: 'Environment intensity',
    lightComposerBackgroundIntensityLabel: 'Background intensity',
    lightComposerBackgroundBlurLabel: 'Background blur',
    lightComposerSourcesTitle: 'Lights',
    lightComposerSourcesEmpty: 'Add at least one source to continue.',
    lightComposerAddSourceCta: 'Add source',
    lightComposerVisibilityCta: 'Toggle visibility',
    lightComposerRemoveSourceCta: 'Remove',
    lightComposerPropertiesTitle: 'Properties',
    lightComposerSourceNameLabel: 'Source name',
    lightComposerScaleLabel: 'Scale',
    lightComposerWidthLabel: 'Width',
    lightComposerHeightLabel: 'Height',
    lightComposerRotationValueLabel: 'Rotation',
    lightComposerLatLonLabel: 'Latlon',
    lightComposerTargetLabel: 'Target',
    lightComposerPaintLightCta: 'Paint Light',
    lightComposerPositionXLabel: 'X',
    lightComposerPositionYLabel: 'Y',
    lightComposerPositionZLabel: 'Z',
    lightComposerColorLabel: 'Color',
    lightComposerIntensityLabel: 'Intensity',
    lightComposerOpacityLabel: 'Opacity',
    lightComposerSizeLabel: 'Size',
    lightComposerTypeLabel: 'Type',
    lightComposerTypeTextureValue: 'texture',
    lightComposerSaveCta: 'Save custom light',
    lightComposerCancelCta: 'Cancel',
    assetTypeScenario: 'Scenario',
    assetTypeObject: 'Object',
    assetTypeLight: 'Light',
    viewIsometric: 'Isometric',
    viewFront: 'Front',
    viewRight: 'Right',
    viewBack: 'Back',
    viewLeft: 'Left',
    viewTop: 'Top',
    originGenerated: 'Generated',
    originLibrary: 'Library',
    originScene: 'Scene',
  },
  status: {
    title: 'Camera status',
    position: 'Position',
    zoom: 'Zoom',
    rotation: 'Rotation',
  },
  hotspotFocusTitle: 'Focused area',
  hotspotFallback: 'Click any marker or scene area to update the camera focus.',
  asset: {
    loading: 'Preparing local 3D asset...',
    loadingDescription: 'Reading temporary manifest and loading model data.',
    missingTitle: '3D asset unavailable',
    missingDescription: 'No local asset matched this creation ID. Run the temporary asset preparation flow and try again.',
    manifestError: 'Could not read temporary local 3D manifest.',
    fallbackPrefix: 'Requested creation',
    formatLabel: 'Format',
    typeLabel: 'Type',
    sourceLabel: 'Source',
  },
  openEditorCta: 'Enable Edit Mode',
  backToGalleryCta: 'Back to Gallery',
  generateNewCta: 'Generate new creation',
};
